### PR TITLE
Sanitize input

### PR DESCRIPTION
**Pull request by markmeyerphoto**
This adds a middleware function that replaces extraneous whitespace like carriage returns and tabs with a space to prevent errors from Watson. It also strips (most) emojis from user input. It is using [emoji-regex](https://www.npmjs.com/package/emoji-regex) to identify emojis. emoji-regex is quite active, so hopefully we will be able to stay on top of the emojis as they change by simply updating the package. 

The middleware function is placed after the feedback middleware where line returns and emojis probably don't hurt and might be part of the feedback.

### CODE REVIEW

**Comment by WolfFlight** [comment]
as a security professional, glad to see that input sanitization is being considered. My initial code review here has not shown me whether or not you are using/storing/accessing data in a database. Sanitizing out things like WHERE, SELECT, *, etc might also be a consideration.

**Comment by tescher** [comment]
If you add a test I'll merge it in :)

**Comment by markmeyerphoto** [comment]
Hey @tescher - I added a handful of tests for this. It was a little different than the others because we want to test the munging of user input before it's get's sent to other apis so we can't just test the return value. I used Sinon to check what was being passed to the middle ware functions, which I think works — it fails when it should and passes when it should.

I'm having issues with some of the Facebook tests working locally but intermittently not working on Travis. It's not giving me a failed test, but a test that can't finish. I'm not sure why, but my hunch is the setTimeout in testFBMsgResponse is maybe too short. Pushing from 500 to 1500 made the tests complete.  But I'm honestly not sure how that test works, so please let me know if it's only passing because I broke it!

**Comment by tescher** [comment]
That should be OK. It might be that Travis is either too fast or too slow
and misses catching the FB response.

Tim Escher
tim@eschers.com
608-432-5799

**Comment by markmeyerphoto** [comment]
Great, thank Tim (and thanks for getting me on the testing bandwagon — I've been meaning to be a little more disciplined about that).

**Pull request merged**
