### PR TITLE
Promisize

### PR DESCRIPTION
**Pull request by markmeyerphoto**
First pass at refactoring.

### CODE REVIEW

**Comment by tescher** [comment]
Hi Mark - Pulled your changes into my VM and tried tests, but it is having trouble with a syntax error:

/usr/bin/node /tmp/nodeunit-intellij-starter.js /usr/local/lib/node_modules/nodeunit test
Testing started at 6:24 AM ...

/home/tescher/node-projects/realtime-bus-sms/routes/index.js:67
        .then((data) => res.render('stop-list-partial', {route:data}))
                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tescher/node-projects/realtime-bus-sms/app.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by markmeyerphoto** [comment]
Hi, I just posted this during the hack night for people to look at. I'm not surprised it doesn't pass tests yet, but it shouldn't be failing with syntax errors. It looks like maybe  it doesn't like es6 arrow functions. What version of Node does this need to run on?

**Comment by tescher** [comment]
I was running 0.10.25. Looks like Travis-CI is running 0.10.48.

Perhaps we need to put node versions into package.json?

Upgraded to 6.8.1 now getting:

/usr/local/bin/node /tmp/nodeunit-intellij-starter.js /usr/local/lib/node_modules/nodeunit test
Testing started at 8:27 AM ...
module.js:471
    throw err;
    ^

Error: Cannot find module '../config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tescher/node-projects/realtime-bus-sms/lib/index.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by markmeyerphoto** [comment]
It's passing all the tests on my end with Node 5.10. But the ()=> notation will be a syntax error on older versions (pre 4.5 I think). They aren't necessary, but really make things more readable, which was one of the things I was hoping to work on.

These are pretty big changes so I would like can talk to the folks on next code for anchorage night and see what everyone thinks before anything gets used.

**Pull request closed without merging**
